sonar.projectKey=kiumarschalangi_transaction-app
sonar.organization=kiumarschalangi

sonar.host.url=https://sonarcloud.io

sonar.sources=lib

sonar.sourceEncoding=UTF-8

# Dart exclusions
sonar.exclusions=**/*.g.dart,**/*.freezed.dart